# Generated by Django 5.2.17 on 2026-09-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], max_length=10)),
                ('name', models.CharField(blank=True, help_text='Required for shared accounts.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Users who may bill to this shared account.', related_name='billing_accounts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Set for personal accounts only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_billing_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_micro', models.BigIntegerField(help_text='Micro-credits. Positive adds credits.')),
                ('kind', models.CharField(choices=[('signup_grant', 'Sign-up grant'), ('admin_grant', 'Admin grant')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='billing.billingaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'personal'), ('owner__isnull', False)), models.Q(('kind', 'shared'), ('owner__isnull', True)), _connector='OR'), name='billing_account_owner_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'personal'), models.Q(('name', ''), _negated=True), _connector='OR'), name='billing_account_shared_needs_name'),
        ),
        migrations.AddConstraint(
            model_name='billingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('owner',), name='billing_account_one_personal_per_user'),
        ),
    ]
