# Generated by Django 5.2.17 on 2026-09-29 07:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Value'), (2, 'Standard'), (3, 'Premium')], unique=True)),
                ('price_per_1k_tokens', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='price per 1K tokens (credits)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_1k_tokens__gte', 0)), name='tier_price_not_negative')],
            },
        ),
    ]
