# Generated by Django 5.2.17 on 2026-09-29 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_backfill_personal_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='price_per_1k_tokens',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Charges only. The tier price when the message was sent.', max_digits=12, null=True, verbose_name='price per 1K tokens (credits)'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tokens',
            field=models.PositiveIntegerField(blank=True, help_text='Charges only. Input + output tokens.', null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('signup_grant', 'Sign-up grant'), ('admin_grant', 'Admin grant'), ('charge', 'Charge')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_micro__lte', 0), ('kind', 'charge'), ('price_per_1k_tokens__isnull', False), ('tokens__isnull', False)), models.Q(models.Q(('kind', 'charge'), _negated=True), ('price_per_1k_tokens__isnull', True), ('tokens__isnull', True)), _connector='OR'), name='ledger_entry_charge_fields'),
        ),
    ]
