# Generated by Django 5.2.17 on 2026-09-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
