# Generated by Django 5.2.17 on 2026-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=20)),
                ('proxy_model_id', models.CharField(help_text='The model ID sent to the proxy.', max_length=100, unique=True)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Value'), (2, 'Standard'), (3, 'Premium')])),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to hide this model from users.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM model',
                'ordering': ['tier', 'display_name'],
            },
        ),
    ]
